name = "Comunismo"
author = "Arthur Bufalo"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5b5d7ff05711486ae88f234221550c031bf68b678a4276abc636cf005286b90"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
